---
- name: Installation of Prometheus
  hosts: pro
  become: true
  gather_facts: false
  tasks:
    - name: Update the systems
      yum:
        name: "*"
        state: latest


    - name: Install some necessary packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - wget
        - vim
        - git
        - net-tools


...