---
- name: Installations of Prometheus
  hosts: local
  become: true
  gather_facts: false
  tasks:
    - name: Update the systems
      ansible.builtin.yum:
        name: "*"
        state: latest
        
    - name: Install some necessary packages
      ansible.builtin.yum:
        name: "{{ packages }}"
      vars:
        packages:
        - wget
        - vim
        - git
        - net-tools
  
    - name:



...